Treinamento Benner/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Treinamento_Benner.Controllers
{
    public class AjaxController : Controller
    {
        //
        // GET: /Ajax/

        public string Index()
        {
            return DateTime.Now.ToString();
        }

    }
}

Treinamento Benner/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Treinamento_Benner.Filters;

namespace Treinamento_Benner.Controllers
{
    [LogActionFilter]
    public class HomeController : Controller
    {
        // GET: /Home/
        public ActionResult Index()
        {
            DateTime data = DateTime.Now;
            return View(data);
        }

        //GET: /Home/Browse?genre=Disco
        public string Browse(string genre)
        {
            string message = HttpUtility.HtmlEncode(
                "Home.Browse, Genre = " + genre);
            return message;
        }
        //GET: /Home/Details/5
        public string Details(int id)
        {
            string message = HttpUtility.HtmlEncode(
                "Home.Details, ID = " + id);
            return message;
        }

        public ViewResult Action()
        {
            ViewBag.Message = "Hello!";
            ViewBag.Date = DateTime.Now;
            return View();
        }

        public RedirectToRouteResult Redirect()
        {
            return RedirectToAction("Action", "Home");
        }

    }
}

Treinamento Benner/Views/Home/Action.cshtml
@{
    ViewBag.Title = "Action";
    Layout = null;
}

<script src="@Url.Content("~/Scripts/angular.min.js")"></script>

<style>
    .sortorder:after{
        content: '\25b2';
    }
    .sortorder.reverse:after{
        content: '\25bc';
    }
</style>

<body ng-app ng-init="aba=1">

  <nav>
      <a href="javascript:;" ng-click="aba=1">Aba 1</a>
      <a href="javascript:;" ng-click="aba=2">Aba 2</a>
      <a href="javascript:;" ng-click="aba=3">Aba 3</a>
  </nav>
    <div ng-if="aba==1"><h1>Aba 1</h1></div>
    <div ng-if="aba==2"><h1>Aba 2</h1></div>
    <div ng-if="aba==3"><h1>Aba 3</h1></div>

</body>

Treinamento Benner/Views/Home/Index.cshtml
@model DateTime
@{
    //Layout = null;
    ViewBag.Title = "Index";
}

@helper ListingItems(params string[] items) {

    <ol>
        @foreach(var item in items){
<li>@item</li>
        }
    </ol>
}

<h2>Linguagens de programação</h2>
@ListingItems("C", "C++", "C#", "F#")
<div id="dummiesList">
    <div class="row">
        <div class="col-xs-12">
            <div class="well">
                <div class="row">
                    <div class="col-xs-12">
                        <h2>Lista de livros</h2>
                        @ListingItems("C for Dummies", "C++ for Dummies", "C# for Dummies", "F# for Dummies")


                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


@section scripts{
    <style>
        p.listrado{
            background-color:#b6ff00;
            color:darkblue;
        }
    </style>
    <script>
        function alternar() {
            $("#terceiro").toggleClass("listrado");
        }
        function count() {
            alert($('p').size());
        }
    </script>
}
<p>Um</p>
<p>II</p>
<p id="terceiro">Terceiro</p>
<input type="button" value="Alternar" onclick="alternar()" />
<input type="button" value="Contar p" onclick="count()" />




<style>
    .red{
        float:left;
        width:100px;
        height: 100px;
        background-color:red;
        margin:10px;
    }
    .clear{clear:both;}
</style>
<script>
    $(function () {
        $("div.red").click(function () {
            $(this).hide('fast');
        });
       
    });
    function divShow() {
        $("div.red:last").show('slow', function() {
            // Use arguments.callee so we don't need a named function
            $(this).prev().show("slow", arguments.callee);
        });
    }
</script>

<div class="red"></div>
<div class="red"></div>
<div class="red"></div>
<div class="red"></div>
<input type="button" value="div show" onclick="divShow()" />


<br />
<hr />

<script>
    $(function () {
        $("[language='German'], [language='English']").hide();
        $("[language='Portuguese']").show();
        $("a[lang]").click(function () {
            $("[language]").hide();
            $("[language=" + $(this).attr("lang") + "]").show();
        });

    });
</script>
<h1 language="Portuguese">Selecionando elementos</h1>
<h1 language="English">Selecting element</h1>
<h1 language="German">Ausw El</h1>

<a href="javascript:;" lang="Portuguese">Português</a>
<a href="javascript:;" lang="English">English</a>
<a href="javascript:;" lang="German">German</a>

<br />
<hr />

<div class="row">
    <div class="col-xs-12">


        <style>
            .tipo {
                margin: 2px;
            }
        </style>
        <script>
            $(function () {
                $('.tipo').each(function () {
                    if ($(this).is('div')) {
                        $(this).css({
                            margin: "5px",
                            width: "50px",
                            heigth: "50px",
                            backgroundColor: "red"
                        });
                    }
                });
            });
        </script>
        <div class="tipo">Nada 1</div>
        <span class="tipo">Nada 2</span>
        <div class="tipo">Nada 3</div>
        <span class="tipo">Nada 4</span>
        <div class="tipo">Nada 5</div>
        <span class="tipo">Nada 6</span>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">


        <script>
            $(function () {
                $('#principal').click(function () {
                    var statusAtual = $(this).is(':checked');
                    $('input[type="checkbox"]').not($(this)).each(function () {
                        $(this).prop('checked', statusAtual);
                    });
                });
            });
        </script>
        <input type="checkbox" id="principal" /><br />
        <input type="checkbox" /><br />
        <input type="checkbox" /><br />
        <input type="checkbox" /><br />
        <input type="checkbox" /><br />
        <input type="checkbox" /><br />
        <input type="checkbox" /><br />
        <input type="checkbox" /><br />
    </div>
</div>

<div class="row">
    <div class="col-xs-12">

        <script>
            $(function () {

                $('p').each(function (i,e) {
                    $('#elemento').append(new Option($(this).html(), i));
                });
           
            });
        
            function seleciona(indice) {
                alert($("p").slice(indice, indice+1).html());
                 console.log($("p")[indice]);
            }
        </script>
        <p>Parágrafo 1</p>
        <p>Parágrafo 2</p>
        <p>Parágrafo 3</p>
        <p>Parágrafo 4</p>
        <p>Parágrafo 5</p>
        <select id="elemento"></select>
        <input type="button" value="Selecionando elemento" onclick="seleciona($('#elemento').val())"/>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <script>
            $(function () {
                $("#alvo").before('<p>Novo elemento antes.</p>');
                $("#alvo").after('<p>Novo elemento depois.</p>');
                $("#alvo").prev().remove();
            });
        </script>
        <p id="alvo">Este é o alvo.</p>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <script>
            //$(function () {
            //    $('div').click(function (event) {
            //        alert('Isso é tudo pessoal!');
            //        $(this).unbind(event);
            //    });
            //    $('div').css({
            //        background: 'red',
            //        width: '200px',
            //        height: '200px'
            //    });
            //});

            ////Iguais.
            //$(function () {
            //    $('div').one('click',function (event) {
            //        alert('Isso é tudo pessoal!');
                   
            //    });
            //    $('div').css({
            //        background: 'red',
            //        width: '200px',
            //        height: '200px'
            //    });
            //});
        </script>
    </div>
</div>


<div class="row">
    <div class="col-xs-12">
        <table id="tabela" class="table">
            <tr>
                <th>Biblioteca</th>
            </tr>
            <tr>                <td>Jquery</td>            </tr>
            <tr>                <td>AngularJS</td>            </tr>
            <tr>                <td>Dojo</td>            </tr>
        </table>
        <script>
            $(function () {
                $("#tabela tr:even").not(":first").css("background-color", "#ccc");
                var corAntiga;
                $("#tabela tr").not(":first").hover(function () {
                    corAntiga = $(this).css("background-color");
                        $(this).css("background-color", "yellow").css("cursor", "pointer");
                }, function () {
                    $(this).css("background-color", corAntiga).css("cursor", "default");
                });
            });
        </script>
    </div>
</div>


<div class="row">
    <div class="col-xs-12">
        <div id="log">

        </div>
        <script>
            $(function () {
                $(document).keyup(function (event) {
                    
                    $("#log").append(String.fromCharCode(event.keyCode) + " - ");
                });
            });
        </script>
    </div>
</div>

<div class="row">
    <div class="col-xs-12">

       
        <div id="alvoAjax"></div>
        <input type="button" class="btn btn-primary" value="Carregar" onclick="carregar()" />

        <script>
            function carregar() {
                $.ajaxSetup({
                    cache:false
                });
                @*$("#alvoAjax").load("@Url.Action("Index", "Ajax")")*@
                
                $.get("@Url.Action("Index", "Ajax")",{ Id: 1, Teste : '2'}, function (result) {
                    $("#alvo").html(result);
                });
            }

        </script>

    </div>
</div>


<div class="row">
    <div class="col-xs-12">


        <script>
            (function ($) {
                $.fn.tornarAzul = function () {
                    return this.css('color', 'blue');
                }
                $.diga = function (texto) {
                    texto = texto || "teste";
                    alert("Eu disse: " + texto);
                }
            })(jQuery);

            $(function () {
                $("#target").tornarAzul();
                $.diga("Olá!");
                $.diga();
            })
        </script>
        <div id="target">Teste</div>
    </div>
</div>